<a href="https://colab.research.google.com/github/srini229/EE5333_tutorials/blob/master/misc/Simplex_single_phase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install mip

In [2]:
import numpy as np
def print_tableau(A, b, c, f):
  for i in range(len(A)):
    print("{0:30} | {1}".format(str(A[i]), b[i]))
  print('_______________________________________')
  print("{0:30} | {1}\n".format(str(c), f))

def simplex(m, obj, verbose = False):
    varMap = {v.name:i for i,v in enumerate(m.vars)}
    numVars = len(m.constrs) + len(m.vars)
    A = np.zeros(shape=(len(m.constrs), numVars))
    c = np.zeros(numVars)
    for i, v in obj.expr.items():
        c[varMap[i.name]] = v
    b = np.zeros(len(m.constrs))
    for i, e in enumerate(m.constrs):
        sens = e.expr.sense
        b[i] = e.rhs if sens == '<' else -e.rhs
        for ind,val in e.expr.expr.items():
            A[i][varMap[ind.name]] = val if sens == '<' else -val
        if sens == '<' or sens == '>': A[i][len(m.vars) + i] = 1
    f = 0
    sol = np.zeros(numVars)

    print("Initial tableau:")
    print_tableau(A, b, c, f)

    ### fill in the simplex core

    print("Final tableau:")
    print_tableau(A, b, c, f)

    print("solution : ", sol, "\n")
    return sol



In [3]:
from mip import Model, maximize

m = Model("test")
x = [m.add_var(), m.add_var()]
obj = m.objective = maximize(x[0] + x[1])
m += x[0] +  3 * x[1] <= 9
m += 2 * x[0] + x[1] <= 8
simplex(m, obj)


m = Model("test")
x = [m.add_var() for i in range(3)]
obj = m.objective = maximize(6 * x[0] + x[1])
m += 9 * x[0] + x[1] + x[2] <= 18
m += 24 * x[0] + x[1] + 4 * x[2] <= 42
simplex(m, obj)

Initial tableau:
[1. 3. 1. 0.]                  | 9.0
[2. 1. 0. 1.]                  | 8.0
_______________________________________
[1. 1. 0. 0.]                  | 0

Final tableau:
[1. 3. 1. 0.]                  | 9.0
[2. 1. 0. 1.]                  | 8.0
_______________________________________
[1. 1. 0. 0.]                  | 0

solution :  [0. 0. 0. 0.] 

Initial tableau:
[9. 1. 1. 1. 0.]               | 18.0
[24.  1.  4.  0.  1.]          | 42.0
_______________________________________
[6. 1. 0. 0. 0.]               | 0

Final tableau:
[9. 1. 1. 1. 0.]               | 18.0
[24.  1.  4.  0.  1.]          | 42.0
_______________________________________
[6. 1. 0. 0. 0.]               | 0

solution :  [0. 0. 0. 0. 0.] 



array([0., 0., 0., 0., 0.])